# -*- coding: utf-8 -*-
"""1.maximum_product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPGy7Uiw8XEfrS9fCyEFMGC1fwg6VVA1
"""

from typing import List

class Solution:
    def maxProduct(self, nums: List[int]) -> int:
        nums.sort()
        a, b = nums[-1], nums[-2]
        return (a - 1) * (b - 1)

# Example run
if __name__ == "__main__":
    sol = Solution()
    print(sol.maxProduct([3, 4, 5, 2]))

