# -*- coding: utf-8 -*-
"""4.steps_reduce_zero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPGy7Uiw8XEfrS9fCyEFMGC1fwg6VVA1
"""

class Solution:
    def numberOfSteps(self, num: int) -> int:
        steps = 0
        while num > 0:
            if num % 2 == 0:
                num //= 2
            else:
                num -= 1
            steps += 1
        return steps

# Example run
if __name__ == "__main__":
    sol = Solution()
    print(sol.numberOfSteps(14))  # Expected: 6

