# -*- coding: utf-8 -*-
"""5.counting_bits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPGy7Uiw8XEfrS9fCyEFMGC1fwg6VVA1
"""

from typing import List

class Solution:
    def countBits(self, n: int) -> List[int]:
        bits = [0] * (n + 1)
        for i in range(1, n + 1):
            bits[i] = bits[i // 2] + (i & 1)
        return bits

# Example run
if __name__ == "__main__":
    sol = Solution()
    print(sol.countBits(5))  # Expected: [0,1,1,2,1,2]

